Repository Selina-Finance/ms-lending-api, pull requests merged in 2022-10, with the labels that each got.

#59 fixed kafka servers name
  src/main/java/com/selina/lending/config/KafkaProducerConfig.java
  src/main/java/com/selina/lending/config/KafkaTopicConfig.java
Labels: approved, size/S

#63 Other: add Roman to owners list
  OWNERS
Labels: approved, size/XS

#64 LA-121
  build.gradle
  src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryImpl.java
  src/main/java/com/selina/lending/internal/service/monitoring/MetricService.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryTest.java
  src/test/java/com/selina/lending/internal/service/monitoring/MetricServiceTest.java
Labels: approved, size/L

#65 LA-63: Add quick quote endpoint and update documentation
  src/main/java/com/selina/lending/api/controller/LendingOperations.java
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/api/controller/QuickQuoteOperations.java
  src/main/java/com/selina/lending/internal/dto/ApplicationResponse.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
Labels: approved, size/L

#66 fixed security intersection
  src/main/java/com/selina/lending/config/security/clientOAuth2/MiddlewareOAuth2Configuration.java
Labels: approved, size/XS

#67 LA-144: Remove prometheus dependency
  build.gradle
Labels: approved, size/XS

#68 LA-147: Revert source change until downstream services support new enum
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryTest.java
Labels: approved, size/XS

#72 LA-137: Add QuickQuoteResponse
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/api/controller/QuickQuoteOperations.java
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuotePropertyDetailsDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteResponse.java
  src/main/java/com/selina/lending/internal/mapper/QuickQuoteApplicationMapper.java
  src/main/java/com/selina/lending/internal/mapper/QuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/internal/mapper/QuickQuotePropertyDetailsMapper.java
  src/main/java/com/selina/lending/internal/mapper/config/QuickQuoteApplicationRequestMapperConfig.java
  src/main/java/com/selina/lending/internal/mapper/config/QuickQuotePropertyDetailsMapperConfig.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
Labels: approved, size/L

#78 LA-167: Add new HOL fields
  src/main/java/com/selina/lending/internal/dto/OfferDto.java
  src/main/java/com/selina/lending/internal/service/application/domain/Offer.java
  src/test/java/com/selina/lending/internal/mapper/ApplicationDecisionResponseMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/ApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
Labels: approved, size/S
