Repository Selina-Finance/ms-lending-api, pull requests merged in 2022-11, with the labels that each got.

#79 LA-162: Add HOL fields for Quick Quote
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteResponse.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/Product.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/ProductOffer.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/L

#80 LA-148: Add Quick Quote to kpis
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestResolver.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapper.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapperTest.java
Labels: approved, size/L

#81 La 154 add req resp to kpi event
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestResolver.java
  src/main/java/com/selina/lending/messaging/event/BrokerRequestKpiEvent.java
  src/main/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapper.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestResolverTest.java
  src/test/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapperTest.java
Labels: approved, size/L

#83 increased brokerKpiEvent size to 20MB
  src/main/java/com/selina/lending/config/KafkaProducerConfig.java
  src/main/java/com/selina/lending/config/KafkaTopicConfig.java
Labels: approved, size/S

#85 LA-174: Amend Circuit Breaker settings and add feign timeout connecti…
  src/main/resources/application.yaml
Labels: approved, size/S

#86 LA-187: Amend delete log and add unit test for FilterServiceImpl
  src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryImpl.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#82 LA-180: Generate swagger.json
  .lighthouse/jenkins-x/pullrequest.yaml
  Makefile
  build.gradle
  generated/swagger-json/swagger.json
  src/main/java/com/selina/lending/api/controller/QuickQuoteOperations.java
  src/main/java/com/selina/lending/internal/dto/FeesDto.java
Labels: approved, size/XXL

#88 LA-183: Run the delete call asynchronously maintaining the trace Id in the thread
  src/main/java/com/selina/lending/config/ThreadConfig.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryImpl.java
Labels: approved, size/M

#92 LA-199: Ensure we are not trying to create two applications that have…
  src/main/java/com/selina/lending/api/errors/custom/BadRequestException.java
  src/main/java/com/selina/lending/internal/service/CreateApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTestController.java
  src/test/java/com/selina/lending/internal/service/CreateApplicationServiceImplTest.java
Labels: approved, size/L

#93 LA-191: Add filter for Accept offers to the filter service and add ad…
  src/main/java/com/selina/lending/internal/api/SelectionServiceApi.java
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/ProductOffer.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/M

#96 LA-201: Add fallback tests
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceFallbackTests.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryFallbackTests.java
Labels: approved, size/L

#97 LA-201: Amend fallback methods and add fallback tests
  src/main/java/com/selina/lending/internal/circuitbreaker/RecordExceptionPredicate.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryImpl.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java
  src/main/resources/application.yaml
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceFallbackTests.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryFallbackTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryFallbackTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryFallbackTests.java
  src/test/resources/application.yml
Labels: size/XL, approved

#98 LA-201: Use predicate in unit test
  src/main/java/com/selina/lending/internal/circuitbreaker/RecordExceptionPredicate.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryTest.java
Labels: approved, size/S
