Repository Selina-Finance/ms-lending-api, pull requests merged in 2022-09, with the labels that each got.

#53 LA 103 add logical response
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestInterceptor.java
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestKpiFilter.java
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestResolver.java
  src/main/java/com/selina/lending/config/KafkaTopicConfig.java
  src/main/java/com/selina/lending/config/WebMvcConfiguration.java
  src/main/java/com/selina/lending/internal/dto/ApplicationDto.java
  src/main/java/com/selina/lending/internal/dto/ApplicationResponse.java
  src/main/java/com/selina/lending/messaging/event/BrokerRequestFinishedEvent.java
  src/main/java/com/selina/lending/messaging/event/BrokerRequestKpiEvent.java
  src/main/java/com/selina/lending/messaging/event/KafkaEvent.java
  src/main/java/com/selina/lending/messaging/publisher/BrokerRequestEventPublisher.java
  src/main/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapper.java
  src/main/java/com/selina/lending/messaging/publisher/mapper/ExternalAppIdHelper.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestInterceptorTest.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestKpiFilterTest.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestKpiResolverTest.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestResolverTest.java
  src/test/java/com/selina/lending/messaging/publisher/BrokerRequestEventPublisherTest.java
  src/test/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapperTest.java
  src/test/java/com/selina/lending/messaging/publisher/mapper/ExternalAppIdHelperTest.java
  src/test/java/com/selina/lending/testHelper/BrokerRequestEventTestHelper.java
Labels: approved, size/XXL

#55 LA-122: Add a new service to verify the access to a specific source a…
  src/main/java/com/selina/lending/internal/service/AccessManagementService.java
  src/main/java/com/selina/lending/internal/service/RetrieveApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/UpdateApplicationServiceImpl.java
  src/test/java/com/selina/lending/internal/service/AccessManagementServiceTest.java
  src/test/java/com/selina/lending/internal/service/RetrieveApplicationServiceImplTest.java
  src/test/java/com/selina/lending/internal/service/UpdateApplicationServiceImplTest.java
Labels: approved, size/L

#56 LA-128: Update log format and add info logs
  src/main/java/com/selina/lending/api/controller/LendingController.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryImpl.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java
  src/main/resources/logback-spring.xml
Labels: approved, size/S

#58 fixed value
  src/main/resources/application.yaml
Labels: approved, size/XS
