Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-03, with the labels that each got.

#136 LA-292: Include the source account in logs
  src/main/java/com/selina/lending/internal/service/CreateApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/RetrieveApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/UpdateApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/creditcommitments/EsisDocServiceImpl.java
  src/main/java/com/selina/lending/internal/service/creditcommitments/RetrieveCreditCommitmentsServiceImpl.java
  src/main/java/com/selina/lending/internal/service/creditcommitments/UpdateCreditCommitmentsServiceImpl.java
Labels: approved, size/S

#137 LA-305: Add Title enum to the PreviousName title
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/internal/dto/DIPApplicantDto.java
  src/main/java/com/selina/lending/internal/dto/FeesDto.java
  src/main/java/com/selina/lending/internal/dto/PreviousNameDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/L

#139 LA-313: Map the maxErc
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/XS

#141 La 314 downstream exceptions handling
  src/main/java/com/selina/lending/api/errors/ErrorConstants.java
  src/main/java/com/selina/lending/api/errors/ExceptionTranslator.java
  src/main/java/com/selina/lending/internal/repository/auth/AuthRepositoryImpl.java
  src/test/java/com/selina/lending/api/controller/auth/AuthControllerWebApiTest.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTestController.java
  src/test/java/com/selina/lending/internal/repository/auth/AuthRepositoryImplTest.java
Labels: approved, size/L

#142 La 316 remove json from error details
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/api/controller/SwaggerConstants.java
  src/main/java/com/selina/lending/api/controller/auth/AuthOperations.java
  src/main/java/com/selina/lending/api/errors/ErrorConstants.java
  src/main/java/com/selina/lending/api/errors/ExceptionTranslator.java
  src/main/java/com/selina/lending/internal/api/AuthApi.java
  src/main/java/com/selina/lending/internal/dto/auth/Credentials.java
  src/main/java/com/selina/lending/internal/repository/auth/AuthRepositoryImpl.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java
  src/test/java/com/selina/lending/internal/repository/auth/AuthRepositoryImplTest.java
Labels: approved, size/L

#143 LA-321: Set the isApplicantResidence flag if it is not set by checkin…
  src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java
  src/main/java/com/selina/lending/internal/service/application/domain/PropertyDetails.java
  src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java
Labels: approved, size/M

#144 Other: Trigger build
  README.md
Labels: approved, size/XS

#145 LA-321: Add check to see if we only have one address and do not set a…
  src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java
  src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java
Labels: approved, size/M

#146 LA-322: Remove Base salary from income type
  src/main/java/com/selina/lending/internal/dto/IncomeItemDto.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
Labels: approved, size/XS, lgtm

#147 LA-323: Add new field for the brokerSubmitterEmail
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/api/controller/SwaggerConstants.java
  src/main/java/com/selina/lending/internal/dto/ApplicantDto.java
  src/main/java/com/selina/lending/internal/dto/ApplicationDecisionResponse.java
  src/main/java/com/selina/lending/internal/dto/DIPApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/DIPCCApplicationRequest.java
  src/main/java/com/selina/lending/internal/service/application/domain/ApplicationRequest.java
  src/test/java/com/selina/lending/internal/mapper/DIPApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/DIPCCApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
Labels: approved, size/L

#150 GRO-1561 HTTP client for creating Quick Quote with Credit Commitments applications
  src/main/java/com/selina/lending/internal/api/MiddlewareApi.java
  src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepository.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java
  src/main/java/com/selina/lending/internal/service/application/domain/quotecc/QuickQuoteCCRequest.java
  src/main/java/com/selina/lending/internal/service/application/domain/quotecc/QuickQuoteCCResponse.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryFallbackTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryTest.java
Labels: approved, size/L
