Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-02, with the labels that each got.

#126 LA-257: Add loan amount and loan term validation
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/internal/dto/ApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/LoanInformationDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationRequest.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
  src/test/java/com/selina/lending/api/validator/EnumValueImplTest.java
Labels: approved, size/L

#127 LA-268: Modify CB settings
  src/main/resources/application.yaml
Labels: approved, size/S

#128 La 264 kpi events redesign
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestKpiFilter.java
  src/main/java/com/selina/lending/api/interceptor/BrokerRequestResolver.java
  src/main/java/com/selina/lending/config/security/SecurityConfig.java
  src/main/java/com/selina/lending/messaging/event/BrokerRequestKpiEvent.java
  src/main/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapper.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestKpiFilterTest.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestResolverTest.java
  src/test/java/com/selina/lending/messaging/publisher/BrokerRequestEventPublisherTest.java
  src/test/java/com/selina/lending/messaging/publisher/mapper/BrokerRequestEventMapperTest.java
  src/test/java/com/selina/lending/testHelper/BrokerRequestEventTestHelper.java
Labels: size/XL, approved

#129 LA-273: Update swagger documentation
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/api/controller/CreditCommitmentsOperations.java
  src/main/java/com/selina/lending/api/controller/DIPOperations.java
  src/main/java/com/selina/lending/api/controller/ProductOperations.java
  src/main/java/com/selina/lending/api/controller/QuickQuoteOperations.java
  src/main/java/com/selina/lending/api/controller/SwaggerConstants.java
  src/main/java/com/selina/lending/api/controller/auth/AuthOperations.java
  src/main/java/com/selina/lending/internal/dto/AddressDto.java
  src/main/java/com/selina/lending/internal/dto/ApplicantDto.java
  src/main/java/com/selina/lending/internal/dto/ApplicationDecisionResponse.java
  src/main/java/com/selina/lending/internal/dto/ApplicationDto.java
  src/main/java/com/selina/lending/internal/dto/CreditCheckDto.java
  src/main/java/com/selina/lending/internal/dto/DIPCCPropertyDetailsDto.java
  src/main/java/com/selina/lending/internal/dto/DIPPropertyDetailsDto.java
  src/main/java/com/selina/lending/internal/dto/EmploymentDto.java
  src/main/java/com/selina/lending/internal/dto/IncomeItemDto.java
  src/main/java/com/selina/lending/internal/dto/LendingConstants.java
  src/main/java/com/selina/lending/internal/dto/LoanInformationDto.java
  src/main/java/com/selina/lending/internal/dto/PriorChargesDto.java
  src/main/java/com/selina/lending/internal/dto/creditcommitments/request/DetailDto.java
  src/main/java/com/selina/lending/internal/dto/creditcommitments/response/DetailResponseDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuotePropertyDetailsDto.java
Labels: size/XL, approved

#130 LA-271: Update test to ensure date pattern as expected and use parame…
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/interceptor/BrokerRequestKpiFilterTest.java
Labels: approved, size/M

#132 LA-281: Update sourceClientId to be mandatory
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/internal/dto/ApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/DIPApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/DIPCCApplicationRequest.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/internal/mapper/DIPCCApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
Labels: approved, size/L

#133 LA-284: Remove startDate from employment object
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/internal/dto/EmploymentDto.java
  src/main/java/com/selina/lending/internal/service/application/domain/Employment.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/L

#134 LA-285: Add max ltv and category
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/ProductOffer.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/L

#135 LA-285: Add category in the offer for DIP responses
  generated/swagger-documentation/lending-api.json
  src/main/java/com/selina/lending/internal/dto/OfferDto.java
  src/main/java/com/selina/lending/internal/service/application/domain/Offer.java
  src/test/java/com/selina/lending/internal/mapper/ApplicationDecisionResponseMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/L
