Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-06, with the labels that each got.

#184 fix(GRO-2057): Add /aggregator path to base URL
  src/main/java/com/selina/lending/internal/enricher/ApplicationResponseEnricher.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/enricher/ApplicationResponseEnricherTest.java
Labels: approved, size/XS

#183 GRO-1985: Provide arrangement fee quick quote endpoint
  src/main/java/com/selina/lending/internal/dto/LendingConstants.java
  src/main/java/com/selina/lending/internal/dto/SourceType.java
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/internal/mapper/quote/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/internal/mapper/quote/middleware/OfferMapper.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/TokenService.java
  src/main/java/com/selina/lending/internal/service/TokenServiceImpl.java
  src/main/java/com/selina/lending/internal/service/application/domain/Fees.java
  src/main/java/com/selina/lending/internal/service/application/domain/Offer.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/Application.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/ProductOffer.java
  src/main/java/com/selina/lending/internal/service/quickquote/ArrangementFeeSelinaService.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quote/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quote/middleware/OfferMapperTest.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
  src/test/java/com/selina/lending/internal/service/TokenServiceImplTest.java
  src/test/java/com/selina/lending/internal/service/quickquote/ArrangementFeeSelinaServiceTest.java
Labels: size/XL, approved

#185 GRO-2133: applicant's identifier is 1 for primaty applicants and is 2 for secondary
  src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java
  src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java
Labels: approved, size/S

#186 chore(GRO-2166): add min max validation on estimated value of property
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuotePropertyDetailsDto.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
Labels: approved, size/M

#191 refactor(GRO-2157): validation on addressdto date fields and new clas…
  src/main/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDate.java
  src/main/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDateImpl.java
  src/main/java/com/selina/lending/config/ObjectMapperConfiguration.java
  src/main/java/com/selina/lending/internal/dto/AddressDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerCircuitBreakerTest.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
  src/test/java/com/selina/lending/api/support/validator/ConditionalImplTest.java
  src/test/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDateImplTest.java
  src/test/java/com/selina/lending/internal/mapper/AddressMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/messaging/mapper/brokerrequest/BrokerRequestEventMapperTest.java
  src/test/resources/__files/ms-lending-api/qq-application-request-bad-date-format.json
Labels: approved, size/L

#190 GRO-2154: Improve number of applicants validation
  src/main/java/com/selina/lending/api/support/validator/MatchNumberOfApplicants.java
  src/main/java/com/selina/lending/api/support/validator/MatchNumberOfApplicantsImpl.java
  src/main/java/com/selina/lending/internal/dto/DIPApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/DIPCCApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationRequest.java
  src/main/java/com/selina/lending/internal/dto/quotecf/QuickQuoteCFApplicationRequest.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
  src/test/java/com/selina/lending/api/support/validator/MatchNumberOfApplicantsImplTest.java
Labels: approved, size/L

#192 improvement(GRO-2184): Add reversion payment amount field to QQ response model
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/S

#194 expect brokerFeesIncluded and brokerFeesUpfront from MW for QQ CF
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/dto/quotecf/QuickQuoteCFApplicationRequest.java
  src/main/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFRequestMapper.java
  src/main/java/com/selina/lending/internal/service/application/domain/quotecf/QuickQuoteCFRequest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFResponseMapperTest.java
Labels: approved, size/M

#195 use new mw dip patch endpoint for dip applications
  src/main/java/com/selina/lending/internal/api/MiddlewareApi.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepository.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java
  src/main/java/com/selina/lending/internal/service/UpdateApplicationServiceImpl.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryTest.java
  src/test/java/com/selina/lending/internal/service/UpdateApplicationServiceImplTest.java
Labels: approved, size/M, lgtm
