Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-04, with the labels that each got.

#154 GRO-1562 filter out declined QuickQuote CC offers
  OWNERS
  src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java
  src/main/java/com/selina/lending/internal/service/CreateApplicationService.java
  src/main/java/com/selina/lending/internal/service/CreateApplicationServiceImpl.java
  src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/service/CreateApplicationServiceImplTest.java
Labels: approved, size/L

#155 GRO-1563: Create endpoint and basic models
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/api/controller/QuickQuoteOperations.java
  src/main/java/com/selina/lending/internal/mapper/QuickQuoteApplicantMapper.java
  src/main/java/com/selina/lending/internal/mapper/QuickQuotePropertyDetailsMapper.java
  src/main/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCRequestMapper.java
  src/main/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapper.java
  src/main/java/com/selina/lending/internal/service/permissions/annotation/Permission.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/QuickQuoteApplicantMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/QuickQuotePropertyDetailsMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapperTest.java
Labels: approved, size/L

#156 add applyUrl to quickQuote response
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/internal/dto/quote/ProductOfferDto.java
  src/main/java/com/selina/lending/internal/enricher/ApplicationResponseEnricher.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/enricher/ApplicationResponseEnricherTest.java
  src/test/resources/application.yml
Labels: approved, size/L

#157 GRO-1788: map missing fields missing quickquotecc
  src/main/java/com/selina/lending/internal/mapper/quotecc/OfferMapper.java
  src/main/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapper.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapperTest.java
Labels: approved, size/S

#158 GRO-1789: Map missed field from MW response
  src/main/java/com/selina/lending/internal/mapper/quotecc/OfferMapper.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapperTest.java
Labels: approved, size/XS

#160 GRO-1791: Income amount value is required
  src/main/java/com/selina/lending/internal/dto/IncomeItemDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/support/validator/EnumValueImplTest.java
Labels: approved, size/L

#161 GRO-1568: include frequency enum in income dto
  .github/pull_request_template.md
  src/main/java/com/selina/lending/internal/dto/IncomeItemDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/M

#163 GRO-1585: validation for expectsFutureIncomeDecrease and reason
  src/main/java/com/selina/lending/internal/dto/IncomeDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/M

#165 GRO-1793: income list object must not be null
  src/main/java/com/selina/lending/internal/dto/IncomeDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/M

#168 meaningful /quickquotecf URL name that stands for the Credit File
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/api/controller/QuickQuoteOperations.java
  src/main/java/com/selina/lending/internal/api/MiddlewareApi.java
  src/main/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricher.java
  src/main/java/com/selina/lending/internal/mapper/quotecc/QuickQuoteCCResponseMapper.java
  src/main/java/com/selina/lending/internal/mapper/quotecf/OfferMapper.java
  src/main/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFRequestMapper.java
  src/main/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFResponseMapper.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepository.java
  src/main/java/com/selina/lending/internal/repository/MiddlewareRepositoryImpl.java
  src/main/java/com/selina/lending/internal/service/CreateApplicationService.java
  src/main/java/com/selina/lending/internal/service/CreateApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/application/domain/quotecf/QuickQuoteCFRequest.java
  src/main/java/com/selina/lending/internal/service/application/domain/quotecf/QuickQuoteCFResponse.java
  src/main/java/com/selina/lending/internal/service/permissions/annotation/Permission.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/enricher/MiddlewareRequestEnricherTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quotecf/QuickQuoteCFResponseMapperTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryFallbackTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryTest.java
  src/test/java/com/selina/lending/internal/service/CreateApplicationServiceImplTest.java
Labels: approved, size/L, lgtm

#169 fix npe raised when offers comes as null
  src/main/java/com/selina/lending/internal/enricher/ApplicationResponseEnricher.java
  src/test/java/com/selina/lending/internal/enricher/ApplicationResponseEnricherTest.java
Labels: approved, size/S

#173 GRO-1846: map offers to middleware create application event
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/config/KafkaProducerConfig.java
  src/main/java/com/selina/lending/internal/mapper/quotecf/OfferMapper.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationService.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/application/domain/Erc.java
  src/main/java/com/selina/lending/internal/service/application/domain/Offer.java
  src/main/java/com/selina/lending/internal/service/application/domain/RuleOutcome.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/ProductOffer.java
  src/main/java/com/selina/lending/messaging/event/middleware/MiddlewareCreateApplicationEvent.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapper.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
  src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
  src/test/java/com/selina/lending/messaging/publisher/MiddlewareCreateApplicationEventPublisherTest.java
Labels: approved, size/L

#175 map offer propertyValueation to a Kafka event
  src/main/java/com/selina/lending/internal/service/application/domain/Offer.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapper.java
  src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
Labels: approved, size/XS
