Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-07, with the labels that each got.

#193 refactor(GRO-2208): add broker fee fields to QQ request and flow
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationRequest.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/internal/mapper/quote/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quote/QuickQuoteApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/internal/mapper/quote/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#197 GRO-2248: additional validation of property details prior charges
  src/main/java/com/selina/lending/api/support/validator/LessThanOrEqualTo.java
  src/main/java/com/selina/lending/api/support/validator/LessThanOrEqualToImpl.java
  src/main/java/com/selina/lending/internal/dto/PriorChargesDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryTest.java
Labels: approved, size/L

#196 refactor(GRO-2240): add partner from keycloak token to QQ request to MW
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationRequest.java
  src/main/java/com/selina/lending/internal/mapper/quote/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/internal/service/application/domain/Partner.java
  src/main/java/com/selina/lending/internal/service/application/domain/quote/middleware/QuickQuoteRequest.java
  src/main/java/com/selina/lending/internal/service/quickquote/PartnerService.java
  src/main/java/com/selina/lending/internal/service/quickquote/PartnerServiceImpl.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/mapper/quote/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
  src/test/java/com/selina/lending/internal/service/quickquote/PartnerServiceImplTest.java
Labels: approved, size/L

#198 fix NPE when applicant's address type is not specified
  src/main/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDateImpl.java
  src/test/java/com/selina/lending/api/support/validator/MoveOutAfterMoveInDateImplTest.java
Labels: approved, size/S

#200 chore(GRO-2313): Add method to enrich request with default fees values
  src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/common/Fees.java
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#202 fix: Make add to loan fields default to false
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/XS

#201 DOPS-925-hpa
  charts/ms-lending-api/templates/hpa.yaml
  charts/ms-lending-api/values.yaml
Labels: approved, size/M
