Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-05, with the labels that each got.

#176 GRO-1921: delete all sending Middleware create application event functionality
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/messaging/event/middleware/MiddlewareCreateApplicationEvent.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/AddressMapper.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeItemMapper.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/IncomeMapper.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/LoanInformationMapper.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapper.java
  src/main/java/com/selina/lending/messaging/mapper/middleware/QuickQuoteApplicantMapper.java
  src/main/java/com/selina/lending/messaging/publisher/MiddlewareCreateApplicationEventPublisher.java
  src/test/java/com/selina/lending/IntegrationTest.java
  src/test/java/com/selina/lending/LendingServiceApplicationTests.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java
  src/test/java/com/selina/lending/config/IntegrationTestConfig.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareApplicationServiceRepositoryFallbackTest.java
  src/test/java/com/selina/lending/internal/repository/MiddlewareRepositoryFallbackTest.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
  src/test/java/com/selina/lending/messaging/mapper/middleware/MiddlewareCreateApplicationEventMapperTest.java
  src/test/java/com/selina/lending/messaging/publisher/MiddlewareCreateApplicationEventPublisherTest.java
  src/test/resources/application.yml
Labels: size/XL, approved, lgtm

#180 Gro 2007 update lending api to include and enrich primary applicant
  src/main/java/com/selina/lending/api/support/validator/MaximumOnePrimaryApplicant.java
  src/main/java/com/selina/lending/api/support/validator/MaximumOnePrimaryApplicantImpl.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicantDto.java
  src/main/java/com/selina/lending/internal/dto/quote/QuickQuoteApplicationRequest.java
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
  src/test/java/com/selina/lending/api/support/validator/MaximumOnePrimaryApplicantImplTest.java
  src/test/java/com/selina/lending/internal/mapper/MapperBase.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
Labels: size/XL, approved

#182 Fix set default primary applicant
  src/main/java/com/selina/lending/internal/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/internal/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M
