Repository Selina-Finance/ms-lending-api, pull requests merged in 2023-08, with the labels that each got.

#203 GRO-2388: set each offer's isAprcHeadline=true while creating QQ for the ClearScore only
  src/main/java/com/selina/lending/api/controller/QuickQuoteController.java
  src/main/java/com/selina/lending/service/enricher/ApplicationResponseEnricher.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerTest.java
  src/test/java/com/selina/lending/service/enricher/ApplicationResponseEnricherTest.java
Labels: approved, size/M

#204 GRO-2371: Allow aggregators to provide incomes on a weekly frequency
  src/main/java/com/selina/lending/api/dto/common/IncomeItemDto.java
Labels: approved, size/S

#206 Gro 2371 delete income frequency field
  src/main/java/com/selina/lending/api/dto/common/IncomeItemDto.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/common/Income.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/M

#208 feat(GRO-2443): Update models to return netLoanAmount
  src/main/java/com/selina/lending/api/dto/qq/response/ProductOfferDto.java
  src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/common/Offer.java
  src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapperTest.java
Labels: approved, size/XS

#210 chore(GRO-2442): Make default values only used if no value is provided
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#211 fix(GRO-2442): Fix offers mapper
  src/main/java/com/selina/lending/api/mapper/qq/middleware/OfferMapper.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
Labels: approved, size/XS

#212 GRO-2471: Disable CSRF protection
  src/main/java/com/selina/lending/config/security/SecurityConfig.java
  src/test/java/com/selina/lending/api/controller/DIPControllerCircuitBreakerTest.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
  src/test/java/com/selina/lending/api/controller/QuickQuoteControllerValidationTest.java
  src/test/java/com/selina/lending/api/controller/auth/AuthControllerWebApiTest.java
  src/test/java/com/selina/lending/api/errors/ExceptionTranslatorTest.java
Labels: approved, size/L

#214 improvement(GRO-2442): Add missing expenditure models
  src/main/java/com/selina/lending/api/mapper/qq/middleware/ExpenditureMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapper.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/qq/request/QuickQuoteRequest.java
  src/main/java/com/selina/lending/httpclient/selection/dto/request/Application.java
  src/main/java/com/selina/lending/httpclient/selection/dto/request/Expenditure.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationRequestMapperTest.java
Labels: approved, size/M
