Repository Selina-Finance/ms-lending-api, pull requests merged in 2024-01, with the labels that each got.

#261 refactor(errorLogging): log Middleware error responses
  src/main/java/com/selina/lending/httpclient/middleware/config/MiddlewareApiErrorDecoder.java
Labels: approved, size/XS

#262 GRO-2814: filter offers for clearscore
  src/main/java/com/selina/lending/httpclient/selection/dto/response/Product.java
  src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
  src/test/resources/application.yml
Labels: approved, size/L

#265 fix(GRO-2839): fix validation for employer name (size must be between 3 and 100)
  src/main/java/com/selina/lending/api/dto/common/EmploymentDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/M

#266 chore(GRO-2813): extended ClearScore alternative offers logic
  src/main/java/com/selina/lending/service/alternativeofferr/AlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/ClearScoreAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/ClearScoreExtendedAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/ExperianAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/MonevoAlternativeOfferRequestProcessor.java
  src/test/java/com/selina/lending/service/alternativeoffer/ClearScoreAlternativeOfferRequestProcessorTest.java
  src/test/java/com/selina/lending/service/alternativeoffer/ClearScoreExtendedAlternativeOfferRequestProcessorTest.java
Labels: approved, size/L

#268 refactor: dummy commit to restart the release pipleine
  src/test/resources/application.yml
Labels: approved, size/S

#269 ST-2150: Return a Decline response with no offers
  src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationRequestMapper.java
  src/main/java/com/selina/lending/httpclient/adp/dto/request/PriorCharges.java
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/S

#271 chore(GRO-2859): filter offers for Experian
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
  src/test/resources/application.yml
Labels: approved, size/L

#272 test(GRO-2859): use Hamcrest matchers instead of AssertJ to check col…
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#275 fix(GRO-2876): expenditure[].balanceDeclared property must be Integer for the Lending API clients
  src/main/java/com/selina/lending/api/dto/common/ExpenditureDto.java
  src/main/java/com/selina/lending/api/mapper/common/ExpendituresMapper.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
Labels: approved, size/S

#276 chore(GRO-2864): handle hasReferOffers flag
  build.gradle
  src/main/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapper.java
  src/main/java/com/selina/lending/httpclient/eligibility/dto/request/Decision.java
  src/main/java/com/selina/lending/httpclient/eligibility/dto/request/EligibilityRequest.java
  src/main/java/com/selina/lending/httpclient/selection/dto/response/FilteredQuickQuoteDecisionResponse.java
  src/main/java/com/selina/lending/repository/EligibilityRepository.java
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/api/mapper/eligibility/EligibilityRequestMapperTest.java
  src/test/java/com/selina/lending/repository/EligibilityRepositoryTest.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L
