Repository Selina-Finance/ms-lending-api, pull requests merged in 2024-05, with the labels that each got.

#306 AM-309: Add feature flag for enabling ADP
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/resources/application.yaml
  src/test/resources/application.yml
Labels: approved, size/S

#307 chore(pre-approval): assume H.F. is always pre-approved
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/util/ABTestUtils.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#308 Revert "chore(pre-approval): assume H.F. is always pre-approved"
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/util/ABTestUtils.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#309 AM-318: Add ltvBand and set the ltvCap to the value of the decimal ve…
  src/main/java/com/selina/lending/api/dto/qq/response/ProductOfferDto.java
  src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapper.java
  src/main/java/com/selina/lending/httpclient/adp/dto/response/ProductOffer.java
  src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java
  src/main/java/com/selina/lending/repository/AdpGatewayRepositoryImpl.java
  src/test/java/com/selina/lending/repository/AdpGatewayRepositoryImplTest.java
Labels: approved, size/M

#310 chore(GRO-3183): delete hasAGarage excess property
  src/main/java/com/selina/lending/api/dto/dip/request/DIPPropertyDetailsDto.java
  src/main/java/com/selina/lending/api/dto/dipcc/request/DIPCCPropertyDetailsDto.java
  src/main/java/com/selina/lending/api/dto/qq/request/QuickQuotePropertyDetailsDto.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/common/PropertyDetails.java
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/api/mapper/common/PropertyDetailsMapperTest.java
Labels: approved, size/S

#311 fix(GRO-3203): return declined QQ response when there are no accepted offers after products filtration
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qqcf/QuickQuoteCFResponseMapperTest.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L
