Repository Selina-Finance/ms-lending-api, pull requests merged in 2024-04, with the labels that each got.

#294 feat(GRO-2960): add default fees for Experian
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#295 Revert "feat(GRO-2960): add default fees for Experian"
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#296 AM-180: Remove unused fields from quick quote and from middleware dtos which are not returned to the client
  src/main/java/com/selina/lending/api/dto/common/OfferDto.java
  src/main/java/com/selina/lending/api/dto/qq/response/ProductOfferDto.java
  src/main/java/com/selina/lending/api/mapper/common/OfferMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/middleware/OfferMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/api/mapper/qqcf/OfferMapper.java
  src/main/java/com/selina/lending/httpclient/adp/dto/response/Product.java
  src/main/java/com/selina/lending/httpclient/adp/dto/response/ProductOffer.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/common/Offer.java
  src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/api/mapper/application/ApplicationDecisionResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/dip/ApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/OfferMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qqcf/QuickQuoteCFResponseMapperTest.java
Labels: approved, size/M

#298 AM-180: Remove fields which are not needed
  src/main/java/com/selina/lending/api/dto/common/OfferDto.java
  src/main/java/com/selina/lending/api/dto/qq/response/ProductOfferDto.java
  src/main/java/com/selina/lending/api/mapper/common/OfferMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/middleware/OfferMapper.java
  src/main/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapper.java
  src/main/java/com/selina/lending/api/mapper/qqcf/OfferMapper.java
  src/main/java/com/selina/lending/httpclient/adp/dto/response/Product.java
  src/main/java/com/selina/lending/httpclient/adp/dto/response/ProductOffer.java
  src/main/java/com/selina/lending/httpclient/middleware/dto/common/Offer.java
  src/main/java/com/selina/lending/httpclient/selection/dto/response/ProductOffer.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/api/mapper/application/ApplicationDecisionResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/dip/ApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/MiddlewareQuickQuoteApplicationRequestMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/middleware/OfferMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qq/selection/QuickQuoteApplicationResponseMapperTest.java
  src/test/java/com/selina/lending/api/mapper/qqcf/QuickQuoteCFResponseMapperTest.java
Labels: approved, size/M

#299 chore(GRO-3035): turn off offers on 5 years tem searches at Experian (A/B test)
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/service/alternativeofferr/AlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/clearscore/ClearScoreAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/experian/ExperianAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/monevo/MonevoAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/util/ABTestUtils.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#300 chore(GRO-3109): filter only Variable rate lowest APRC offer for Experian CreditMatcher partner
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#301 chore(GRO-3105): allow the 1700-01-01 as the earliest date for all date fields
  src/main/java/com/selina/lending/api/controller/SwaggerConstants.java
  src/main/java/com/selina/lending/api/dto/common/EmploymentDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/S

#302 chore(GRO-3128): allow applicants employer name to be 2 characters long
  src/main/java/com/selina/lending/api/dto/common/EmploymentDto.java
  src/test/java/com/selina/lending/api/controller/DIPControllerValidationTest.java
Labels: approved, size/XS

#304 AM-244: Default isAprcHeadline to false and amend property default va…
  src/main/java/com/selina/lending/api/mapper/qq/adp/QuickQuoteEligibilityApplicationResponseMapper.java
  src/main/java/com/selina/lending/repository/AdpGatewayRepositoryImpl.java
Labels: approved, size/XS
