Repository Selina-Finance/ms-lending-api, pull requests merged in 2024-03, with the labels that each got.

#284 AM-4: Route ms-quick-quote requests to adp if the feature is enabled
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
  src/test/resources/application.yml
Labels: approved, size/M

#285 chore(GRO-3003): decline 5-year searches for ClearScore
  src/main/java/com/selina/lending/service/alternativeofferr/clearscore/ClearScoreAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/clearscore/ClearScoreExtendedAlternativeOfferRequestProcessor.java
  src/main/java/com/selina/lending/service/alternativeofferr/clearscore/ClearScoreKeepOriginalRequestedLoanTermAlternativeOfferRequestProcessor.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
  src/test/java/com/selina/lending/service/alternativeoffer/clearscore/ClearScoreAlternativeOfferRequestProcessorTest.java
  src/test/java/com/selina/lending/service/alternativeoffer/clearscore/ClearScoreBasicAlternativeOfferRequestProcessorTest.java
  src/test/java/com/selina/lending/service/alternativeoffer/clearscore/ClearScoreExtendedAlternativeOfferRequestProcessorTest.java
  src/test/java/com/selina/lending/service/alternativeoffer/clearscore/ClearScoreKeepOriginalTermAlternativeOfferRequestProcessorTest.java
Labels: size/XL, approved

#286 Revert "feat(GRO-2960): add default fees for Experian"
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M

#287 chore(GRO-2936): A/B pre-approvals test
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/util/ABTestUtils.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#290 ops(gcp migration): update chartmuseum url
  preview/helmfile.yaml
Labels: approved, size/XS

#289 chore(GRO-2859): filter Experian response offers only for GoCompare partner
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/L

#291 chore(GRO-2888): AB test fixed vs variable rate offers for ClearScore
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/main/java/com/selina/lending/util/ABTestUtils.java
  src/test/java/com/selina/lending/api/mapper/MapperBase.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
  src/test/java/com/selina/lending/util/ABTestUtilsTest.java
Labels: approved, size/L

#292 AM-30: Filter out Decline offers and update url for eligibility
  src/main/java/com/selina/lending/httpclient/adp/AdpGatewayApi.java
  src/main/java/com/selina/lending/httpclient/adp/dto/response/QuickQuoteEligibilityDecisionResponse.java
  src/main/java/com/selina/lending/service/FilterApplicationServiceImpl.java
  src/test/java/com/selina/lending/service/FilterApplicationServiceImplTest.java
Labels: approved, size/M
